openapi: 3.0.0
info:
  title: Phone number verification API with Swagger
  version: 1.0.0
  description: Phone number verification api with swagger
servers:
  - url: http://localhost:8001
paths:
  /register:
    post:
      summary: Register phone number
      description: Register phone number
      requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    phoneNumber:
                      type: string
                      example: 828888888                   
      responses:
        200:
          description: A list of users. 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    phonenumber:
                      type: string
                      example: 8283333333
